# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3437b21087647370c292da71c78f072cac112ba96f4c28e6944bc34a5731f5e43868db0def5c7aab86ceba8d38632a11857366ad6b159d7df0bd2f2c6035f2c9

test:
  secret_key_base: 8536f35ba1912fe497b443d4a080625bd6ddd8f902b6ebc404b71c292b0b06915e233798ca77c39b7d418dec58e3d5733cb9f6c9035b6a3336cc2f175c1f78d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
