tcs:
  send_xml_server:
    ip: 127.0.0.1
    port: 55555
  receive_xml_server:
    ip: 127.0.0.1
    port: 44444
device_management:
  robot:
    ip: 127.0.0.1
    send_port: 11111
    receive_port: 11112
  wms:
    ip: 127.0.0.1
    send_port: 22222
    receive_port: 22223
  nc:
    ip: 127.0.0.1
    send_port: 33333
    receive_port: 33334
mqtt:
  ip: 127.0.0.1
duiduoche:
  ip: 192.168.7.5
  port: 502
nc:
  nc1:
    ip: 192.168.5.52
  nc2:
    ip: 192.168.5.53
host:
  ip: 192.168.1.157
  port: 3000

robot_plc:
  ip: 192.168.5.10